### ISSUE TITLE
Create and Manage Available Schedules for Providers

### ISSUE THREAD

**Issue by DerekAyala** [BrightCoders-Institute/proyecto-final-oppenbarbies#73]
## DESCRIPTION

Develop the feature that allows providers to create and manage their available schedules. This includes defining time slots, marking availability, and ensuring that this information is visible to clients.

"More specifically, send the data to Firebase after selecting the unavailable dates."

```[tasklist]
### Tasks
- [x] Design the data structure for available schedules in Firestore.
- [x] Implement logic to save and display available schedule data.
```

**Comment by Antonio3veces3** [comment]
Well done!
